services:
  api-gateway:
    image: charmflex/microservices-grocery-api-gateway:latest
    ports:
      - "9000:9000"
    environment:
      GATEWAY_AUTH_SECRET: ${GATEWAY_AUTH_SECRET}
      IDENTITY_URL: ${IDENTITY_URL}
      INVENTORY_URL: ${INVENTORY_URL}

  identity-service:
    image: charmflex/microservices-grocery-auth-service:latest
#    ports:
#      - "3011:3001"
    environment:
      GATEWAY_AUTH_SECRET: ${GATEWAY_AUTH_SECRET}
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    depends_on:
      auth-db:
        condition: service_healthy


  inventory-service:
    image: charmflex/microservices-grocery-inventory-service:latest
#    ports:
#      - "3012:3002"
    environment:
      GATEWAY_AUTH_SECRET: ${GATEWAY_AUTH_SECRET}
      POSTGRES_USER: ${POSTGRES_USER_INVENTORY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_INVENTORY}
      POSTGRES_DB: ${POSTGRES_DB_INVENTORY}
    depends_on:
      inventory-db:
        condition: service_healthy
#
#  notification-service:
#    image: charmflex/microservices-grocery-notification-service:latest
#    ports:
#      - "3003:3003"
#    environment:
#      GATEWAY_AUTH_SECRET: ${GATEWAY_AUTH_SECRET}

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000



  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
      #      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'

  inventory-db:
    image: "postgres:17"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_INVENTORY}
      POSTGRES_USER: ${POSTGRES_USER_INVENTORY}
      POSTGRES_DB: ${POSTGRES_DB_INVENTORY}
    volumes:
      - postgres_v17_data_inventory:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER_INVENTORY}", "-d", "${POSTGRES_DB_INVENTORY}", ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      options:
        max-size: 10m

  auth-db:
    image: "postgres:17"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    volumes:
      - postgres_v17_data_auth:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER_AUTH}", "-d", "${POSTGRES_DB_AUTH}", ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      options:
        max-size: 10m


volumes:
  postgres_v17_data_auth:
  postgres_v17_data_inventory:


