services:
#  app:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile
#    ports:
#      - "3002:3000"
#    depends_on:
#      db:
#        condition: service_healthy

  db:
    image: "postgres:17"
    #ports:
     # - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_v17_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      options:
        max-size: 10m

volumes:
  postgres_v17_data:

