global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:9000'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'identity-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['identity-service:3001'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Identity Service'
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:3002'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Inventory Service'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:3003'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Notification Service'
